services:
  mediaklikk-proxy:
    image: ghcr.io/smart123s/mediaklikk-proxy
    container_name: mediaklikk-proxy
    environment:
      - PORT=80
      - BASE_URL=http://localhost:80
    restart: always
    ports:
      - 80:80
